# Generated by Django 4.1 on 2022-09-04 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_store_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmodel',
            old_name='name',
            new_name='title',
        ),
    ]
