# Generated by Django 4.1 on 2022-09-04 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_store_app', '0002_rename_name_bookmodel_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='stock',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
