# Generated by Django 4.1 on 2022-09-04 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_store_app', '0003_bookmodel_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='stock',
            field=models.IntegerField(default=1),
        ),
    ]
