# Generated by Django 4.1 on 2022-09-18 01:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('book_store_app', '0005_addressmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileDataModel',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('country', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=250)),
                ('zip_or_postal_code', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('book_coins', models.FloatField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='price',
            field=models.FloatField(default=1),
        ),
        migrations.DeleteModel(
            name='AddressModel',
        ),
    ]
