# Generated by Django 4.1 on 2022-09-18 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_store_app', '0006_profiledatamodel_bookmodel_price_delete_addressmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiledatamodel',
            name='address',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='profiledatamodel',
            name='book_coins',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='profiledatamodel',
            name='city',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profiledatamodel',
            name='country',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='profiledatamodel',
            name='phone',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='profiledatamodel',
            name='zip_or_postal_code',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
