# Generated by Django 4.1 on 2022-09-18 11:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_store_app', '0008_userpurchasehistorymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpurchasehistorymodel',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='userpurchasehistorymodel',
            name='qty',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
