# Generated by Django 4.1 on 2022-09-18 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book_store_app', '0009_userpurchasehistorymodel_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpurchasehistorymodel',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
