# Generated by Django 4.1 on 2022-09-19 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_store_app', '0011_alter_userpurchasehistorymodel_book_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiledatamodel',
            name='book_coins',
            field=models.FloatField(blank=True, default=20, null=True),
        ),
        migrations.AlterField(
            model_name='profiledatamodel',
            name='phone',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
